const express = require("express");
const response = express.Router();
const admins = require("../controllers/admincontroller.jsx");
response.get("/viewusers", admins.viewusers);
response.post("/acceptusers/:id", admins.acceptusers);
response.post("/create", admins.create);
response.get("/viewrejected", admins.viewrejected);
response.post("/deleterejected/:id", admins.deleterejected);
response.post("/rejectusers/:id", admins.rejectusers);
response.post("/acceptrejectedusers/:id", admins.acceptrejectedusers);
response.get("/viewpending", admins.viewpending);
response.get("/viewloans", admins.viewloans);
response.post("/createloan", admins.createLoan);
response.put("/updateuser/:id", admins.editusers);
response.delete("/deleteusers/:id", admins.deleteusers);
response.put("/updateloans/:id", admins.editloans);
response.delete("/deleteloans/:id", admins.deleteloans);
module.exports = response;
