const express = require("express");
const response = express.Router();
const admins = require("../controllers/admincontroller.jsx");
response.get("/viewusers/:email", admins.viewusers);
response.post("/acceptusers/:id", admins.acceptusers);
response.post("/rejectusers/:id", admins.rejectusers);
response.post("/acceptrejectedusers/:id", admins.acceptrejectedusers);
response.get("/viewpending", admins.viewpending);
response.post("/createloan", admins.createLoan);
module.exports = response;
``;
